server:
  port: 8080
  read_timeout: 60
  write_timeout: 60
  base_path: ""

tts:
  region: "eastasia"
  default_voice: "zh-CN-XiaoxiaoNeural"
  default_rate: "0"
  default_pitch: "0"
  default_format: "audio-24khz-48kbitrate-mono-mp3"
  max_text_length: 65535
  request_timeout: 30
  max_concurrent: 20
  segment_threshold: 300
  min_sentence_length: 200
  max_sentence_length: 300
  api_key: ''

  # 长文本处理优化配置
  long_text:
    enabled: true                    # 启用长文本优化处理
    max_segment_length: 500          # 每个分段最大字符数（建议 400-600）
    worker_count: 5                  # 并发 worker 数量（建议 3-10）
    min_text_for_split: 1000         # 触发分段的最小文本长度
    ffmpeg_path: ""                  # FFmpeg 路径（留空使用系统 PATH）
    use_smart_segment: true          # 使用智能分段（基于句子边界）
    use_ffmpeg_merge: true           # 使用 FFmpeg 合并音频（推荐开启）

  # OpenAI 到微软 TTS 中文语音的映射
  voice_mapping:
    alloy: "zh-CN-XiaoyiNeural"       # 中性女声
    echo: "zh-CN-YunxiNeural"         # 年轻男声
    fable: "zh-CN-XiaochenNeural"     # 儿童声
    onyx: "zh-CN-YunjianNeural"       # 成熟男声
    nova: "zh-CN-XiaohanNeural"       # 活力女声
    shimmer: "zh-CN-XiaomoNeural"     # 温柔女声
openai:
  api_key: ''

ssml:
  # preserve_tags 不再需要，因为新的SSML处理器会自动保留所有标签。
  # 保留空的ssml键以确保配置加载正确。
log:
  level: "info"
  format: "text" # "json" or "text"

cache:
  enabled: true
  expiration_minutes: 1440 # 缓存过期时间（分钟），1天
  cleanup_interval_minutes: 1440 # 缓存清理间隔（分钟），1天